# config.yml

#  _____                                                     _____
# ( ___ )                                                   ( ___ )
#  |   |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|   |
#  |   |  ____  _                 _       ____               |   |
#  |   | | __ )| | ___   ___   __| |_   _| __ )  __ _ _ __   |   |
#  |   | |  _ \| |/ _ \ / _ \ / _` | | | |  _ \ / _` | '_ \  |   |
#  |   | | |_) | | (_) | (_) | (_| | |_| | |_) | (_| | | | | |   |
#  |   | |____/|_|\___/ \___/ \__,_|\__, |____/ \__,_|_| |_| |   |
#  |   |                            |___/                    |   |
#  |___|~~~~~~~~~~~~~~~~~~~~~~~~Config~~~~~~~~~~~~~~~~~~~~~~~|___|
# (_____)                                                   (_____)

# Кастомная команда бана (по умолчанию tempban (CMI))
banCommand: tempban

# Время бана (Мин)
banDurationMinutes: 1

# Сообщение
banMessage: "Смерть"

#Тонкая настройка времени в тиках (время после смерти)
timeBefore: 10