name: BloodyBan
version: '${version}'
main: org.quelicori.bloodyban.BloodyBan
api-version: '1.16'

commands:
  bloodyban:
    description:
    permission: bloodyban.owner
    permission-message: у вас нет прав)
    usage: /bloodyban <exempt|unexempt|reload>
